apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pvc-pod
spec:
  containers:
    - name: test-container
      image: busybox:latest
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date +'%Y-%m-%d %H:%M:%S') >> /mnt/pvc/data.txt; sleep 60; done"]
      volumeMounts:
        - name: pvc-storage
          mountPath: /mnt/pvc
  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: test-pvc
